### PR TITLE
Fix syncing block entity attachments on load.

### LINKED ISSUE #4389: Accessing world too early in attachment deserialization
```
[Server thread/ERROR] (Minecraft) Failed to load data for block entity minecraft:jukebox
 java.lang.NullPointerException: Cannot invoke "net.minecraft.world.World.getRegistryManager()" because "this.world" is null
	at knot/net.minecraft.block.entity.BlockEntity.fabric_getDynamicRegistryManager(BlockEntity.java:1176) ~[minecraft-merged-228b57201f-1.21.1-net.fabricmc.yarn.1_21_1.1.21.1+build.3-v2.jar:?]
	at knot/net.minecraft.block.entity.BlockEntity.acknowledgeSynced(BlockEntity.java:695) ~[minecraft-merged-228b57201f-1.21.1-net.fabricmc.yarn.1_21_1.1.21.1+build.3-v2.jar:?]
	at knot/net.minecraft.block.entity.BlockEntity.md0ab4de$fabric-data-attachment-api-v1$lambda$fabric_readAttachmentsFromNbt$0$0(BlockEntity.java:677) ~[minecraft-merged-228b57201f-1.21.1-net.fabricmc.yarn.1_21_1.1.21.1+build.3-v2.jar:?]
	at java.base/java.util.IdentityHashMap.forEach(IdentityHashMap.java:1375) ~[?:?]
	at knot/net.minecraft.block.entity.BlockEntity.fabric_readAttachmentsFromNbt(BlockEntity.java:675) ~[minecraft-merged-228b57201f-1.21.1-net.fabricmc.yarn.1_21_1.1.21.1+build.3-v2.jar:?]
	at knot/net.minecraft.block.entity.BlockEntity.handler$zef000$fabric-data-attachment-api-v1$readBlockEntityAttachments(BlockEntity.java:1137) ~[minecraft-merged-228b57201f-1.21.1-net.fabricmc.yarn.1_21_1.1.21.1+build.3-v2.jar:?]
	at knot/net.minecraft.block.entity.BlockEntity.read(BlockEntity.java:156) ~[minecraft-merged-228b57201f-1.21.1-net.fabricmc.yarn.1_21_1.1.21.1+build.3-v2.jar:?]
```
`fabric-api 0.114.0+1.21.1`
[latest.log](https://github.com/user-attachments/files/18474566/latest.log)

### PR DESCRIPTION
**Pull request by modmuss50**
Not the cleanest change, but should do the job no worse than before.

Closes #4389

Needs backporting to 1.21.1

### CODE REVIEW

File: fabric-data-attachment-api-v1/src/testmod/java/net/fabricmc/fabric/test/attachment/AttachmentTestMod.java [hunk 1]
```diff
@@ -92,5 +97,18 @@ public void onInitialize() {
...
 				RegistryKey.of(RegistryKeys.PLACED_FEATURE, Identifier.of(MOD_ID, "set_attachment"))
 		);
+
+		UseBlockCallback.EVENT.register((player, world, hand, hitResult) -> {
+			if (player.getStackInHand(hand).getItem() == Items.CARROT) {
+				BlockEntity blockEntity = world.getBlockEntity(hitResult.getBlockPos());
+
+				if (blockEntity != null) {
+					blockEntity.setAttached(SYNCED_WITH_ALL, true);
+					player.sendMessage(Text.literal("Attached"), false);
```
Comment (Octol1ttle) [inline fabric-data-attachment-api-v1/src/testmod/java/net/fabricmc/fabric/test/attachment/AttachmentTestMod.java:107]: should return success here?

Comment (modmuss50) [reply fabric-data-attachment-api-v1/src/testmod/java/net/fabricmc/fabric/test/attachment/AttachmentTestMod.java:107]: Fixed, thanks.
