### PR TITLE
Fix nether portal crash

### LINKED ISSUE #1255: fabric-entity-events-v1 crash with entities moving through Nether portals
When placing an entity in a Nether portal that has not generated an exit, a NullPointerException is thrown because `null` is returned by `L/Entity;moveToWorld(LServerWorld;)LEntity;` when the `teleportTarget` is `null`.

This line attempts to access the `world` field on the returned value (which may be `null`):
https://github.com/FabricMC/fabric/blob/36111fa0e17dee082fd1a600365b24925c712b03/fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/EntityMixin.java#L38

Log of an example crash:
```
java.lang.NullPointerException
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7)
    at net.minecraft.entity.Entity.handler$zgb000$afterWorldChanged(Entity:5150)
    at net.minecraft.entity.Entity.moveToWorld(Entity:2326)
    at net.minecraft.entity.Entity.tickNetherPortal(Entity:1942)
    at net.minecraft.entity.Entity.baseTick(Entity:449)
    at net.minecraft.entity.LivingEntity.baseTick(LivingEntity:324)
    at net.minecraft.entity.mob.MobEntity.baseTick(MobEntity:275)
    at net.minecraft.entity.Entity.tick(Entity:431)
    at net.minecraft.entity.LivingEntity.tick(LivingEntity:2209)
    at net.minecraft.entity.mob.MobEntity.tick(MobEntity:342)
    at net.minecraft.entity.mob.ZombieEntity.tick(ZombieEntity:233)
    at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:621)
    at net.minecraft.world.World.tickEntity(World:561)
    at net.minecraft.server.world.ServerWorld.tick(ServerWorld:411)
    at net.minecraft.server.MinecraftServer.redirect$zoi000$ficUpdateSuppressionCrashTick(MinecraftServer:6207)
    at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:871)
    at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:312)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811)
    at net.minecraft.server.MinecraftServer.handler$baa000$modifiedRunLoop(MinecraftServer:7310)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:651)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
    at java.lang.Thread.run(Unknown Source)
```

### PR DESCRIPTION
**Pull request by magneticflux-**
Closes #1255 

Entities can exist in uninitialized portals again:

### CODE REVIEW

File: fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/EntityMixin.java [hunk 1]
```diff
@@ -33,8 +33,16 @@
...
+	/**
+	 * Select ordinal 2 for the "happy path" of teleportation (this.world instanceof ServerWorld, !this.removed, teleportTarget != null).
+	 * The returned entity can still be null if it is unable to be created by {@link net.minecraft.entity.EntityType#create(World)}.
+	 */
+	@Inject(method = "moveToWorld", at = @At(value = "RETURN", ordinal = 2))
 	private void afterWorldChanged(ServerWorld destination, CallbackInfoReturnable<Entity> cir) {
-		ServerEntityWorldChangeEvents.AFTER_ENTITY_CHANGE_WORLD.invoker().afterChangeWorld((Entity) (Object) this, cir.getReturnValue(), (ServerWorld) this.world, (ServerWorld) cir.getReturnValue().world);
+		// Ret will only have an entity if entity was successfully created
+		Entity ret = cir.getReturnValue();
+		if (ret != null) {
```
Comment (i509VCB) [inline fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/EntityMixin.java:41]: Whitespace between if def and entity - this will fail checkstyle

**Review by i509VCB — APPROVED** [review]
Other than checkstyle I have verified this fix is correct

**Review by modmuss50 — APPROVED** [review]
