### PR TITLE
24w06a porting fixes

### LINKED ISSUE #3554: [1.20.4] `CommonLifecycleEvents#TAGS_LOADED` isn't called on client thread when joining a world
The callback is supposed to run with the `client` flag set to `true` when the client receives the tag sync packet from the server. 

Currently this does not happen for both joining a singleplayer world and clients connecting to a dedicated server.

The callback however does run perfectly fine with the `client` flag set to `true` after executing `/reload`.

The callback on the server thread seems to work fine (when `client` is set to `false`).

### PR DESCRIPTION
**Pull request by apple502j**
Surprisingly, Resource Loader and RegSync needed zero changes with regard to vanilla RegSync feature. We can utilize this, but it is kept for later.

- Bump yarn
- Refactor some code to 1) adopt Yarn rename of "resource pack names" to IDs, 2) to match vanilla coding style (with respect to isInCreativeMode)
- Resolves #3554 
- Fixes a bug where using a custom elytra did not clear the new field, `ignoreFallDamageAboveY`.

### CODE REVIEW

**Review by modmuss50 — APPROVED** [review]

File: fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/elytra/PlayerEntityMixin.java [hunk 1]
```diff
@@ -56,6 +61,7 @@ void injectElytraCheck(CallbackInfoReturnable<Boolean> cir) {
 
 		if (EntityElytraEvents.CUSTOM.invoker().useCustomElytra(self, false)) {
 			startFallFlying();
+			this.ignoreFallDamageAboveY = null;
```
Comment (modmuss50) [inline fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/elytra/PlayerEntityMixin.java:64]: Great spot with this one 👍
