### PR TITLE
Fix Biome API bugs

### LINKED ISSUE #2127: Crash when `WeightedPicker#search` called with argument out of expected range
The following error crashed my server several times while generating terrain for `minecraft:the_end` with [Chunky](https://github.com/pop4959/Chunky)

```
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: The provided target value for entry selection must be less than or equal to the weight total
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalArgumentException: The provided target value for entry selection must be less than or equal to the weight total
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at net.fabricmc.fabric.impl.biome.WeightedPicker.search(WeightedPicker.java:79)
	at net.fabricmc.fabric.impl.biome.WeightedPicker.pickFromNoise(WeightedPicker.java:56)
	at net.fabricmc.fabric.impl.biome.TheEndBiomeData$Overrides.pick(TheEndBiomeData.java:132)
	at net.minecraft.class_2169.handler$zzc000$getWeightedEndBiome(class_2169.java:546)
	at net.minecraft.class_2169.method_38109(class_2169.java:82)
	at net.minecraft.class_2826.method_38291(class_2826.java:200)
	at net.minecraft.class_2791.method_38257(class_2791.java:393)
	at net.minecraft.class_3754.method_38327(class_3754.java:134)
	at net.minecraft.class_3754.method_38333(class_3754.java:124)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more
```
A full crash report is available [here](https://mclo.gs/tMcyWWH)

Is this an issue with the Fabric API, as it appears?

### LINKED ISSUE #2259: Crash at the world creation screen with datapack content added through the Biome API
The game crashes when trying to create a world, if a mod with datapack content that is added through the Biome API is installed.
As a clear example, Promenade features Nether and End biomes and features that are now added by the mod's datapack (see commit https://github.com/DawnTeamMC/Promenade/commit/0e14663a8093a43ce420ed3f0958c8d13bbca925 and this [crash log](https://bytebin.lucko.me/SVmrvc6iGj)) and then added to vanilla generation through the Biome API, which is part of the Fabric API.

In vanilla Minecraft, when you try to create a world, the vanilla builtin worldgen gets loaded, and then opens the screen with the loaded generic content. However the Biome API lets us add to the vanilla generation by adding `RegistryKey`s, but actually requires these keys to represent built-in content so that it gets loaded on this specific screen. This constraint should not exist, and as a fix the Fabric API must tell the game to load the mod datapacks at the same time as builtin Minecraft worldgen content on this screen.

### LINKED ISSUE #2292: Custom End biomes crash
When using the Fabric API test mod in the End (`/execute in the_end run tp @s 0 256 2000`):

```
java.lang.IllegalStateException: seed isn't set, ChunkGenerator hook not working?
	at net.fabricmc.fabric.impl.biome.TheEndBiomeData$Overrides.getSampler(TheEndBiomeData.java:163)
	at net.fabricmc.fabric.impl.biome.TheEndBiomeData$Overrides.pick(TheEndBiomeData.java:155)
	at net.fabricmc.fabric.impl.biome.TheEndBiomeData$Overrides.pick(TheEndBiomeData.java:136)
	at net.minecraft.class_2169.handler$zzd000$getWeightedEndBiome(class_2169.java:546)
	at net.minecraft.class_2169.method_38109(class_2169.java:71)
	at net.minecraft.class_3195.method_41613(class_3195.java:145)
	at net.minecraft.class_3195.method_41614(class_3195.java:124)
	at net.minecraft.class_2794.method_41044(class_2794.java:636)
	at net.minecraft.class_2794.method_41041(class_2794.java:589)
```

### LINKED ISSUE #2310: Biome API relies on RegistryEntry identity, which is not guaranteed
To fix this:

- `IdentityHashMap` needs to be replaced with `Object2ObjectOpenCustomHashMap` + custom `Hash.Strategy`.
- `a == b` needs to be replaced with `a.matches(b::matchesKey)`. (Only works for reference entries, but biome api shouldn't encounter direct entry.)

### LINKED ISSUE #2311: Off-by-one error in end midlands/barrens generation
https://github.com/FabricMC/fabric/blob/23acfcd6a18d1c956b9c8ff55ed89dae7ef4228e/fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/TheEndBiomeData.java#L125

This incorrectly returns `true` if a modded highlands biome has exactly one associated modded midlands/barrens biome, causing vanilla midlands/barrens to generate instead. L151 also has the same error.

### PR DESCRIPTION
**Pull request by apple502j**
Fixes #2127 
Fixes #2259 
Fixes #2292 
Fixes #2310 
Fixes #2311 
Closes #2301 

# Changes
- End biomes are loaded lazily to allow data pack DRM entries to be used.
- Nether biomes are modified just before `ServerWorld` gets created to allow data pack DRM entries to be used. There aren't many other injection points which allow this sort of stuff, because `MultiNoiseBiomeSource` gets created too early.
- @deirn 's fix: Fixes crash with modded End biomes due to missing seed.
- deirn's fix: Fixes biome set not being modified for End biomes.
- `TheEndBiomeData` no longer assumes identity of `RegistryEntry`. See #2310 for solutions. This includes custom `Hash.Strategy` for them (used for fastutil hashmaps/hashsets) which we might want to expose in Registry Sync.
- If modded highlands has exactly one modded midlands/barrens, they now generate, instead of vanilla ones. This is caused by an off-by-one error in the code.
- Clamps the perlin noise value in `WeightedPicker` to fix a crash. As noted in #2127 perlin noises can in rare cases go outside `0 <= n < 1` range. Clamping should not mess up worldgen because it's very rare from my understanding, and weird generation is better than a crash.
- deirn's refactor: `MultiNoiseSampler` now stores the perlin noise sampler directly instead of using a map. Might work as a performance optimization, unsure.

### CODE REVIEW

File: fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/NetherBiomeData.java [hunk 1]
```diff
@@ -65,10 +76,43 @@ public static boolean canGenerateInNether(RegistryKey<Biome> biome) {
...
+	private static MultiNoiseUtil.Entries<RegistryEntry<Biome>> withModdedBiomeEntries(MultiNoiseUtil.Entries<RegistryEntry<Biome>> entries, Registry<Biome> biomeRegistry) {
+		if (NETHER_BIOME_NOISE_POINTS.isEmpty()) {
+			return entries;
+		}
+
+		ArrayList<Pair<MultiNoiseUtil.NoiseHypercube, RegistryEntry<Biome>>> entryList = new ArrayList<>(entries.getEntries());
+
+		for (Map.Entry<RegistryKey<Biome>, MultiNoiseUtil.NoiseHypercube> entry : NETHER_BIOME_NOISE_POINTS.entrySet()) {
+			if (biomeRegistry.contains(entry.getKey())) {
+				LOGGER.info("Nether biome {} loaded successfully", entry.getKey().getValue());
```
Comment (maityyy) [inline fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/NetherBiomeData.java]: Is it really necessary? I would not like unnecessary logs in my console

Comment (apple502j) [reply fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/NetherBiomeData.java]: > Also logging needs to be removed before we merge.

**Comment by modmuss50** [comment]
I have added a command to this PR to help test the other issues. Hope you dont mind.

**Comment by apple502j** [comment]
@modmuss50 great! ~~will also fix the seed issue soonish~~ nvm #2301

**Comment by apple502j** [comment]
Updated, ready to review.

File: fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/TheEndBiomeData.java [hunk 2]
```diff
@@ -103,26 +114,27 @@ public static class Overrides {
 
 		// cache for our own sampler (used for random biome replacement selection)
 		private final Map<MultiNoiseUtil.MultiNoiseSampler, PerlinNoiseSampler> samplers = new WeakHashMap<>();
-		// current seed, set from ChunkGenerator hook since it is not normally available
-		private static ThreadLocal<Long> seed = new ThreadLocal<>();
 
 		public Overrides(Registry<Biome> biomeRegistry) {
```
Comment (deirn) [inline fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/TheEndBiomeData.java:116]: What about saving this registry in a field and just using the static biome _key_ maps to pick a replacement?

File: fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/TheEndBiomeData.java [hunk 3]
```diff
@@ -159,18 +175,37 @@ private synchronized PerlinNoiseSampler getSampler(MultiNoiseUtil.MultiNoiseSamp
 			PerlinNoiseSampler ret = samplers.get(noise);
```
Comment (deirn) [inline fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/TheEndBiomeData.java]: https://github.com/apple502j/fabric/pull/1 :tiny_potato:

File: fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/TheEndBiomeData.java (hunk 2 above)
Comment (apple502j) [reply fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/TheEndBiomeData.java:116]: Could work. I didn’t refactor most of the code but I suppose it makes the stuff overall better and more performance efficient.

Comment (apple502j) [reply fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/TheEndBiomeData.java:116]: Now that I think about it, storing registry entry might be more efficient because `pick` I believe is called often.

**Review by modmuss50 — APPROVED** [review]
Looks great, thanks everyone for the help 👍 

I'm quite happy to get this out now unless anyone has any objections?
