### PR TITLE
Fabric Networking API V1

### LINKED ISSUE #187: ClientSidePacketRegistry.INSTANCE.register can be called on dedi server, resulting in crash
`ClientSidePacketRegistry.INSTANCE.register()` doesn't have an embedded environment check, so if the code gets called on a dedicated server, it will crash due to NoClassDefFoundError for MinecraftClient.

### LINKED ISSUE #345: Expose NetworkHandler or ClientConnection to clientside network events, fix player retrieval
MC creates and sets the player on the client thread by synchronizing the join packet, which happens after receiving other packets.

In the meanwhile `PacketContext.getPlayer()` returns null and the connection is not easily unobtainable for an immediate reply (only reflectively from `MinecraftClient.clientConnection`, `ConnectScreen.connection` or `RealmsConnect.connection` depending on the connection origin).

The potential null result and thread unsafety[1] of `PacketContext.getPlayer()` is problematic, maybe it's better to block its use on the network threads. Most of those uses are likely a bug, with the most significant exception being the serverside `NetworkThreadUtils.forceMainThread(..., player.getServerWorld())`, which could be replaced by exposing the server conveniently instead.

[1] There are no guarantees on the chronologically "correct" value propagating without proper synchronization. It may be significantly delayed or even sporadically revert to an outdated value between consecutive field reads (e.g. thread moved between cores and new core's cache has older state).

### PR DESCRIPTION
**Pull request by i509VCB**
This is partially based of off and supersedes #605. This pull request is based off the `feature/cut` branch on the fablabs drafting repository. This pull request was primarily written by @liach but has been adapted into a new pull request on the FabLabs fabric api fork to continue the pull request.

This pull request migrates the networking api to v1 and deprecates the old api (minus player streams which need to be migrated by a different pull request). The old networking api is re-implemented using the new networking api in a backwards compatible way.

Registration of custom packet handlers is now done through the client or server networking's play receiver. The interface used to read the packet and apply (originally PacketConsumer) is now much more ergonomic, as it exposes the client and serve respectively along with the network handler. This effectively resolves #345.

This pull request also adds the ability for mods to send and handle login query messages. This allows the client and server to communicate much earlier and delay login for the client/server until tasks have been completed on either side (async tasks included).

Events related to the connection/disconnection of the client or server were added to the respective `Client/ServerConnectionEvents`. This effectively resolves #247

Also resolves #187, and prepares the groundwork for a system described in #164.

### CODE REVIEW

File: fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ClientConnectionEvents.java [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+			callback.onPlayInitialized(handler, client, sender);
+		}
+	});
+
+	/**
+	 * An event for the disconnection of the client play network handler.
+	 *
+	 * <p>No packets should be sent when this event is invoked.
+	 */
+	public static final Event<PlayDisconnected> PLAY_DISCONNECTED = EventFactory.createArrayBacked(PlayDisconnected.class, callbacks -> (handler, client) -> {
```
Comment (RDIL) [inline fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ClientConnectionEvents.java]: This might just be my computer but it looks like this indent is different then below?

Comment (i509VCB) [reply fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ClientConnectionEvents.java]: I think GH is funky with tabs sometimes

File: fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ChannelHandlerRegistry.java [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+/**
+ * Associates packets to individual packet reception handlers by channel.
+ *
+ * @param <H> the channel handler type
+ */
+public interface ChannelHandlerRegistry<H> extends ChannelRegistry {
+	/**
+	 * Registers a handler to a channel.
+	 *
+	 * <p>If a handler is already registered to the {@code channel}, this method will return {@code false}, and no change will be made.
```
Comment (ghost) [inline fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ChannelHandlerRegistry.java]: `this method should return {@code false}` because ultimately implementation details can't definitively be known by interface exposure, but we can suggest that would be the norm

File: fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ClientChannelEvents.java [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+/**
+ * Offers access to events related to the registration of network channels for a client-side network handler.
+ */
+@Environment(EnvType.CLIENT)
+public final class ClientChannelEvents {
+	/**
+	 * An event for the client play network handler receiving an update indicating the connected server's ability to receive packets in certain channels.
+	 *
+	 * @see PlayPacketSender#hasChannel(Identifier)
+	 */
```
Comment (ghost) [inline fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ClientChannelEvents.java]: This could be further clarified. At first glance understanding what this does is a little difficult. Like when exactly does this trigger.

File: fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ClientChannelEvents.java [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+		for (Registered callback : callbacks) {
+			callback.onChannelRegistered(handler, client, sender, channels);
+		}
+	});
+
+	/**
+	 * An event for the client play network handler receiving an update indicating the connected server's lack of ability to receive packets in certain channels.
+	 *
+	 * @see PlayPacketSender#hasChannel(Identifier)
+	 */
```
Comment (ghost) [inline fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ClientChannelEvents.java]: Same here

File: fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ClientNetworking.java [hunk 5]
```diff
@@ -0,0 +1,151 @@
...
+	 * @return the associated packet sender
+	 */
+	public static PlayPacketSender getPlaySender(ClientPlayNetworkHandler handler) {
+		return ClientNetworkingDetails.getAddon(handler);
+	}
+
+	/**
+	 * Returns the packet receiver for channel handler registration on client play network handlers, receiving {@link net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket server to client custom payload packets}.
+	 */
+	public static ChannelHandlerRegistry<PlayChannelHandler> getPlayReceiver() {
```
Comment (ghost) [inline fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ClientNetworking.java]: I might change this to `getPlayReceivers` to clarify that this isn't returning one specific play receiver but a registry of play receivers

File: fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ClientNetworking.java [hunk 6]
```diff
@@ -0,0 +1,151 @@
...
+		return ClientNetworkingDetails.PLAY;
+	}
+
+	/**
+	 * Returns the packet receiver for channel handler registration on client login network handlers, receiving {@link net.minecraft.network.packet.s2c.login.LoginQueryRequestS2CPacket login query request packets}.
+	 */
+	public static ChannelHandlerRegistry<LoginChannelHandler> getLoginReceiver() {
```
Comment (ghost) [inline fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ClientNetworking.java]: Same here `getLoginReceivers`

File: fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ClientNetworking.java [hunk 7]
```diff
@@ -0,0 +1,151 @@
...
+		return ClientNetworkingDetails.LOGIN;
+	}
+
+	/**
+	 * Sends a packet to the connected server.
+	 *
+	 * @param channel the channel of the packet
+	 * @param buf the payload of the packet
+	 */
+	public static void send(Identifier channel, PacketByteBuf buf) {
```
Comment (ghost) [inline fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ClientNetworking.java]: Doesn't this have the opportunity to throw an exception? If so, that should be mentioned in the javadoc.

Comment (ghost) [inline fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ClientNetworking.java]: Also maybe there should be a method similar to `getPlaySender(ClientPlayNetworkHandler handler)` and `getPlaySender() throws IllegalStateException` that is `send(ClientPlayNetworkHandler handler, Identifier channel, PacketByteBuf buf)`

File: fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ClientNetworking.java [hunk 8]
```diff
@@ -0,0 +1,151 @@
...
+	@Environment(EnvType.CLIENT)
+	@FunctionalInterface
+	public interface PlayChannelHandler {
+		/**
+		 * Handles an incoming packet.
+		 *
+		 * <p>This method is executed on {@linkplain io.netty.channel.EventLoop netty's event loops}.
+		 * Modification to the game should be {@linkplain net.minecraft.util.thread.ThreadExecutor#submit(Runnable) scheduled} using the provided Minecraft client instance.
+		 *
+		 * <p>An example usage of this is to display a
```
Comment (ghost) [inline fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ClientNetworking.java]: Where did the rest of this sentence go. I'm dying to know what it says

File: fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/PlayPacketSender.java [hunk 9]
```diff
@@ -0,0 +1,29 @@
...
+
+package net.fabricmc.fabric.api.networking.v1;
+
+import net.minecraft.util.Identifier;
+
+/**
+ * Supports sending packets to channels in the play network handlers.
+ *
+ * <p>Compared to a simple packet sender, the play packet sender is informed if its connected recipient may {@link #hasChannel(Identifier) accept packets in certain channels}.
+ * <!--TODO: Implement use of system property-->
```
Comment (ghost) [inline fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/PlayPacketSender.java]: Just highlighting this as something that is on the to-do list for others looking at this review to get a synopsis

File: fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ServerChannelEvents.java [hunk 10]
```diff
@@ -0,0 +1,66 @@
...
+		for (Registered callback : callbacks) {
+			callback.onChannelRegistered(handler, server, sender, channels);
+		}
+	});
+
+	/**
+	 * An event for the server play network handler receiving an update indicating the connected client's lack of ability to receive packets in certain channels.
+	 *
+	 * @see PlayPacketSender#hasChannel(Identifier)
+	 */
```
Comment (ghost) [inline fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ServerChannelEvents.java]: Similar to the comment I made on the client side, more specifics about when this occurs would be good in the javadoc

File: fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ServerChannelEvents.java [hunk 11]
```diff
@@ -0,0 +1,66 @@
...
+
+/**
+ * Offers access to events related to the registration of network channels for a server-side network handler.
+ */
+public final class ServerChannelEvents {
+	/**
+	 * An event for the server play network handler receiving an update indicating the connected client's ability to receive packets in certain channels.
+	 *
+	 * @see PlayPacketSender#hasChannel(Identifier)
+	 */
```
Comment (ghost) [inline fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ServerChannelEvents.java]: Same here see below

File: fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/AbstractChanneledNetworkAddon.java [hunk 12]
```diff
@@ -0,0 +1,173 @@
...
+
+import net.minecraft.network.ClientConnection;
+import net.minecraft.network.PacketByteBuf;
+import net.minecraft.util.Identifier;
+import net.minecraft.util.InvalidIdentifierException;
+
+import net.fabricmc.fabric.api.networking.v1.PacketByteBufs;
+import net.fabricmc.fabric.api.networking.v1.PlayPacketSender;
+
+// play
```
Comment (ghost) [inline fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/AbstractChanneledNetworkAddon.java]: What's this comment for?

File: fabric-networking-v0/src/main/java/net/fabricmc/fabric/impl/networking/OldNetworkingHooks.java [hunk 13]
```diff
@@ -0,0 +1,36 @@
...
+ * limitations under the License.
+ */
+
+package net.fabricmc.fabric.impl.networking;
+
+import net.fabricmc.api.ModInitializer;
+import net.fabricmc.fabric.api.event.network.C2SPacketTypeCallback;
+import net.fabricmc.fabric.api.networking.v1.ServerChannelEvents;
+
+public final class OldNetworkingHooks implements ModInitializer {
```
Comment (ghost) [inline fabric-networking-v0/src/main/java/net/fabricmc/fabric/impl/networking/OldNetworkingHooks.java:23]: This is definitely me missing the point, but what is this for exactly?

**Review by ghost — APPROVED** [review]
Everything looks good I mainly just had some minor concerns over some of the documentation and beefing that up. After looking through it for a while it actually wasn't that bad making sense of all of it, but for the average user this whole module is kind of overwhelming so having more details about exactly when certain events are occurring and that sort of thing might be helpful. Other than that I saw a couple places where there were TODOs floating around, some of them looked like integrations with future modules, some just looked like things that have yet to be done. Regardless I'm sure they're in the works and will be done before final pull. To me it looks pretty good I don't really have any concerns. The one design detail I was hesitant about was having only a single handler per channel but that seems best for simplicity and people who want multiple handlers per channel just need to fix their impl because the only way I could see you wanting that would be from trying to implement a badly designed idea.

File: fabric-networking-v0/src/main/java/net/fabricmc/fabric/impl/networking/OldNetworkingHooks.java (hunk 13 above)
Comment (i509VCB) [reply fabric-networking-v0/src/main/java/net/fabricmc/fabric/impl/networking/OldNetworkingHooks.java:23]: That class implements the old `PacketType` events using the new `ClientChannelEvents` and `ServerChannelEvents`

File: fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ChannelHandlerRegistry.java (hunk 2 above)
Comment (i509VCB) [reply fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ChannelHandlerRegistry.java]: Imo specifying semantics are fine in javadoc for an interface

**Review by Player3324 — APPROVED** [review]
API looks good, thanks for this extensive effort!

File: fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/client/networking/v1/ClientLoginConnectionEvents.java [hunk 14]
```diff
@@ -0,0 +1,99 @@
...
+import net.minecraft.client.MinecraftClient;
+import net.minecraft.client.network.ClientLoginNetworkHandler;
+
+import net.fabricmc.fabric.api.event.Event;
+import net.fabricmc.fabric.api.event.EventFactory;
+
+/**
+ * Offers access to events related to the connection to a server on the client while the server is processing the client's login request.
+ */
+public final class ClientLoginConnectionEvents {
```
Comment (shedaniel) [inline fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/client/networking/v1/ClientLoginConnectionEvents.java:31]: This (and its inner classes) should be annotated with @Environment(EnvType.CLIENT)

File: fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/PlayerLookup.java [hunk 15]
```diff
@@ -0,0 +1,193 @@
...
+	 * @param radius the maximum distance from the position in blocks
+	 * @return the players around the position
+	 */
+	public static Collection<ServerPlayerEntity> around(ServerWorld world, Vec3d pos, double radius) {
+		double radiusSq = radius * radius;
+
+		return world(world)
+				.stream()
+				.filter((p) -> p.squaredDistanceTo(pos) <= radiusSq)
+				.collect(Collectors.toList());
```
Comment (shedaniel) [inline fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/PlayerLookup.java:169]: Would returning an `Iterable` or `Iterator` be sufficient in order to not creating a list?

Comment (Player3324) [reply fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/PlayerLookup.java:169]: Having the size is quite nice and it needs to create something, the (Array)List should be one of the cheapest options.

**Review by sschr15 — COMMENTED** [review]
The copyright in the headers does not include 2020

**Comment by haykam821** [comment]
Don't worry, that isn't new: #598

**Comment by i509VCB** [comment]
The license header year will be handled later when I make Fabric API use JDK style license headers

File: fabric-player-tracking-api-v1/src/main/resources/fabric.mod.json [hunk 16]
```diff
@@ -0,0 +1,26 @@
+{
```
Comment (modmuss50) [inline fabric-player-tracking-api-v1/src/main/resources/fabric.mod.json]: I dont think this player tracking stuff belongs here? The module is not included in gradle?

File: fabric-networking-api-v1/src/testmod/java/net/fabricmc/fabric/test/networking/login/NetworkingLoginQueryTest.java [hunk 17]
```diff
@@ -0,0 +1,76 @@
...
+		ServerLoginConnectionEvents.LOGIN_QUERY_START.register(this::onLoginStart);
+		ServerLoginConnectionEvents.LOGIN_QUERY_START.register(this::delaySimply);
+
+		// login delaying example
+		ServerLoginNetworking.registerGlobalReceiver(NetworkingPlayPacketTest.TEST_CHANNEL, (server, handler, understood, buf, synchronizer, sender) -> {
+			if (understood) {
+				FutureTask<?> future = new FutureTask<>(() -> {
+					for (int i = 0; i <= 10; i++) {
+						Thread.sleep(300);
+						NetworkingTestmods.LOGGER.info("Delayed login for number {} 300 milliseconds", i);
```
Comment (modmuss50) [inline fabric-networking-api-v1/src/testmod/java/net/fabricmc/fabric/test/networking/login/NetworkingLoginQueryTest.java]: Disable this by default, its a fine test just dont really want this all the time when using the test mods :D

File: fabric-networking-api-v1/src/testmod/java/net/fabricmc/fabric/test/networking/keybindreciever/NetworkingKeybindPacketTest.java [hunk 18]
```diff
@@ -0,0 +1,54 @@
...
+	private static void receive(MinecraftServer server, ServerPlayerEntity player, PacketByteBuf buf, PacketSender responseSender) {
+		// TODO: Can we send chat off the server thread?
+		server.execute(() -> {
+			player.sendMessage(new LiteralText("So you pressed ").append(new KeybindText("fabric-networking-api-v1-testmod-keybind").styled(style -> style.withFormatting(Formatting.BLUE))), false);
+		});
+	}
+
+	@Override
+	public void onInitialize() {
+		// FIXME: DO NOT LET ME PR THIS BEFORE FIXING IT
```
Comment (modmuss50) [inline fabric-networking-api-v1/src/testmod/java/net/fabricmc/fabric/test/networking/keybindreciever/NetworkingKeybindPacketTest.java]: Need fixing apparenly.

**Review by modmuss50 — CHANGES_REQUESTED** [review]
Looking really good 👍 few very minor things around the test mods.

This will need a decent amount of testing, including vanilla/mutliversion servers (where we have had issues before).

File: fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/QueryIdFactory.java [hunk 19]
```diff
@@ -0,0 +1,39 @@
...
+package net.fabricmc.fabric.impl.networking.server;
+
+import java.util.concurrent.atomic.AtomicInteger;
+
+/**
+ * Tracks the current query id used for login query responses.
+ */
+interface QueryIdFactory {
+	static QueryIdFactory create() {
+		// todo incremental ids or randomized
```
Comment (FlashyReese) [inline fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/QueryIdFactory.java]: Is already done? Should remove

**Review by modmuss50 — APPROVED** [review]
Awesome 🍾 

Nice work, the API looks solid 👍

**Review by sschr15 — APPROVED** [review]

**Review by FlashyReese — APPROVED** [review]

**Review by marcus8448 — APPROVED** [review]

**Review by NeusFear — APPROVED** [review]

**Comment by NeusFear** [comment]
Sorry, had stashed comments apparently.

**Review by LambdAurora — APPROVED** [review]

**Review by OroArmor — APPROVED** [review]
Ok its time to merge this in

**Comment by modmuss50** [comment]
Lets go 🚀 

Thanks for this.
