### PR TITLE
Fix Bug in LootTableEvents.MODIFY_DROPS causing inline loot tables to always throw (Breaking Change)

### LINKED ISSUE #4681: Error when executing data pack function using FAPI in 1.21.6 pre-3
```
[14:56:15] [Server thread/WARN]: Failed to execute function pandamium:startup/place_dummy_blocks
java.lang.IllegalStateException: LootTable appears to be unregistered, but has been asked to generate loot
	at knot/net.fabricmc.fabric.impl.loot.LootUtil.lambda$getEntry$2(LootUtil.java:71) ~[fabric-loot-api-v3-1.1.0+9889468542-dbce32c098484123.jar:?]
	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at knot/net.fabricmc.fabric.impl.loot.LootUtil.getEntry(LootUtil.java:70) ~[fabric-loot-api-v3-1.1.0+9889468542-dbce32c098484123.jar:?]
	at knot/net.minecraft.class_52.wrapMethod$zem000$fabric-loot-api-v3$fabric$modifyDrops(class_52.java:1050) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_52.method_328(class_52.java) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_52.method_320(class_52.java:115) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_52.method_319(class_52.java:132) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_52.method_51878(class_52.java:127) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3039.method_13180(class_3039.java:433) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3039.method_13197(class_3039.java:416) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3039.method_13177(class_3039.java:97) ~[server-intermediary.jar:?]
	at knot/com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
	at knot/net.minecraft.class_8865.method_54416(class_8865.java:29) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8865.execute(class_8865.java:13) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8856.method_54405(class_8856.java:8) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8847.method_54388(class_8847.java:8) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8854.method_54390(class_8854.java:107) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2170.method_54313(class_2170.java:420) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2991.method_12904(class_2991.java:70) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_231.method_17938(class_231.java:17) ~[server-intermediary.jar:?]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at knot/net.minecraft.class_231.method_967(class_231.java:17) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_231.method_974(class_231.java:9) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_236.method_988(class_236.java:84) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_29203(class_3218.java:433) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_18765(class_3218.java:338) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1063) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:947) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:707) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:291) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
```

### PR DESCRIPTION
**Pull request by cputnam-a11y**
Fixes #4681 by passing Direct entries when the table is unregistered and adds inline table tests to the tested

### CODE REVIEW

File: fabric-loot-api-v3/src/main/java/net/fabricmc/fabric/impl/loot/LootUtil.java [hunk 1]
```diff
@@ -67,8 +68,7 @@ public static RegistryEntry.Reference<LootTable> getEntry(ServerWorld world, Loo
 				.streamEntries()
 				.filter(it -> it.value().equals(table))
 				.findFirst()
-				.orElseThrow(
-						() -> new IllegalStateException("LootTable appears to be unregistered, but has been asked to generate loot")
-				);
+				.map(Function.<RegistryEntry<LootTable>>identity())
```
Comment (Juuxel) [inline fabric-loot-api-v3/src/main/java/net/fabricmc/fabric/impl/loot/LootUtil.java:71]: A cast might be better (but I doubt it matters a lot)

**Review by PepperCode1 — APPROVED** [review]

File: fabric-loot-api-v3/src/testmod/java/net/fabricmc/fabric/test/loot/LootTest.java [hunk 2]
```diff
@@ -167,12 +175,50 @@ public void onInitialize() {
...
+			try {
+				recGuard2.setTrue();
+				actionGetter.apply(context.getWorld().getServer()).run();
+			} finally {
+				recGuard2.setFalse();
+			}
+		});
+	}
+
+	@SuppressWarnings("SameParameterValue")
```
Comment (Juuxel) [inline fabric-loot-api-v3/src/testmod/java/net/fabricmc/fabric/test/loot/LootTest.java]: I don't think FAPI generally uses SuppressWarnings for IDEA inspections

**Review by Juuxel — APPROVED** [review]
The test is a bit complex with the cached command etc, but I don't think it's worth rewriting to spawn the loot directly.

**Comment by cputnam-a11y** [comment]
> The test is a bit complex with the cached command etc, but I don't think it's worth rewriting to spawn the loot directly.

I think this was intentional. I needed an inline table, and wanted one from vanilla
I guess an easier way to say it would be, I wanted to reproduce the issue lol. It is a simplified version of the command originally exposing the issue

File: fabric-loot-api-v3/src/main/java/net/fabricmc/fabric/impl/loot/LootUtil.java (hunk 1 above)
Comment (cputnam-a11y) [reply fabric-loot-api-v3/src/main/java/net/fabricmc/fabric/impl/loot/LootUtil.java:71]: Yeah, don't think it really matter. We're just going to a super type

**Review by modmuss50 — APPROVED** [review]
