### PR TITLE
Fix registry sync namespace check

### LINKED ISSUE #2348: Fabric Registry Sync marks command argument type registry as modded, even if it's not
It's caused by vanilla using `brigadier` namespace for some entries.

Related line: https://github.com/FabricMC/fabric/blob/1.19/fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/MixinSimpleRegistry.java#L58

### PR DESCRIPTION
**Pull request by apple502j**
Resolves #2348 
Should also work as a bandaid fix for #2315 (although I bet this would just make the bug more obscure)

### CODE REVIEW

**Comment by modmuss50** [comment]
Test seems to be failing: `Attempted to register object test twice! (at raw IDs 0 and 1 )`

File: fabric-registry-sync-v0/src/testmod/java/net/fabricmc/fabric/test/registry/sync/RegistrySyncTest.java [hunk 1]
```diff
@@ -109,6 +109,15 @@ public void onInitialize() {
...
 		Validate.isTrue(!RegistryAttributeHolder.get(fabricRegistry).hasAttribute(RegistryAttribute.PERSISTED));
 
+		SimpleRegistry<String> fakeVanillaRegistry = FabricRegistryBuilder.createSimple(String.class, new Identifier("registry_sync", "fake_vanilla_registry"))
+				.attribute(RegistryAttribute.SYNCED)
+				.buildAndRegister();
+
+		Registry.register(fakeVanillaRegistry, new Identifier("minecraft", "test"), "test");
+		Registry.register(fakeVanillaRegistry, new Identifier("brigadier", "test"), "test");
+
+		Validate.isTrue(!RegistryAttributeHolder.get(fakeVanillaRegistry).hasAttribute(RegistryAttribute.MODDED));
```
Comment (modmuss50) [inline fabric-registry-sync-v0/src/testmod/java/net/fabricmc/fabric/test/registry/sync/RegistrySyncTest.java]: This test wont work, as all registries created through the builder are marked as modded. I cannot think of a good way to "unit" test this. I will fix and manuall test. 👍

**Review by modmuss50 — APPROVED** [review]
Change works well, tested with a fabric api server with gametest module, and a prod fabric api client. 👍

**Review by Player3324 — APPROVED** [review]
