### PR TITLE
port(26.1)!: `fabric-renderer-api-v1`

### LINKED ISSUE #5253: Missing `fabric-renderer-*`
I noticed what `fabric-renderer-*` is in the github repository, but when I add Fabric API as a dependency, `fabric-renderer-*` doesn't load. That is, there is no in Intellij IDEA.

Is this an API issue or did I do something wrong?

By `fabric-renderer-*` I mean: `fabric-renderer-api-v1` and `fabric-renderer-indigo`.

### PR DESCRIPTION
**Pull request by sylv256**
If you would like to work on this PR, ask me to add you as a collaborator on my fork, and please discuss in the FRAPI Development thread in the Discord server.

## Renderer
Large API changes. `Renderer` now has three methods for creating a `BlockQuadOutput`-like `QuadEmitter`, an `AltModelBlockRenderer` (`ModelBlockRenderer` alternative), and a `MutableMesh` (as before).

## QuadEmitter
`Renderer#quadEmitter(Consumer<? extends MutableQuadView>)` creates a new `QuadEmitter` that accepts the `Consumer` upon emission.

## AltModelBlockRenderer
The `AltModelBlockRenderer` is an alternative to `ModelBlockRenderer` that allows tessellating a `BlockStateModel` through a `QuadEmitter`

## General Changes
 - `FabricSpriteGetter` is now `FabricMaterialBaker`.
 - Many structures in Indigo have been moved to FRAPI to reduce maintenance burden.

fixes #5253

### CODE REVIEW

File: fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/api/client/model/loading/v1/SimpleUnbakedExtraModel.java [hunk 1]
```diff
@@ -76,10 +78,27 @@ public static SimpleUnbakedExtraModel<BlockStateModel> blockStateModel(Identifie
...
+			QuadCollection quads = baked.bakeTopGeometry(
+					textures,
+					baker,
+					settings
+			);
+
+			boolean hasTranslucency = false;
+
+			// SimpleModelWrapper#bake does this as well
+			for (BakedQuad quad : quads.getAll()) {
```
Comment (PepperCode1) [inline fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/api/client/model/loading/v1/SimpleUnbakedExtraModel.java]: Always check `instanceof MeshQuadCollection` before calling methods on the `QuadCollection`. If `SimpleModelWrapper` also does this then it needs to be patched to support meshes.

File: fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/client/renderer/v1/mesh/MutableQuadView.java [hunk 2]
```diff
@@ -278,18 +277,25 @@ default MutableQuadView normal(int vertexIndex, Vector3fc normal) {
...
-	 * <p>If set to {@code null}, {@link ItemBlockRenderTypes#getChunkRenderType(BlockState)} will be used to retrieve
-	 * the {@linkplain ChunkSectionLayer chunk layer} in block contexts. Set to another value to override this behavior.
-	 *
-	 * <p>In block contexts, a non-null value will be used directly. In item contexts, any value will be converted to a
-	 * {@link RenderType} using {@link FabricLayerRenderState#setRenderTypeGetter(ItemRenderTypeGetter)}.
+	 * <p>If set to {@code null}, {@link ModelHelper#getSpriteInfo(TextureAtlasSprite)} will be used to retrieve
+	 * the {@linkplain ChunkSectionLayer chunk layer}. Set to another value to override this behavior.
 	 *
 	 * <p>The default value is {@code null}.
 	 */
```
Comment (PepperCode1) [inline fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/client/renderer/v1/mesh/MutableQuadView.java:371]: Add

```
<p>This property is respected only in block contexts. It will not have an effect in other contexts.
```

after the default value paragraph.

File: fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/client/renderer/v1/mesh/MutableQuadView.java [hunk 3]
```diff
@@ -278,18 +277,25 @@ default MutableQuadView normal(int vertexIndex, Vector3fc normal) {
...
 	MutableQuadView chunkLayer(@Nullable ChunkSectionLayer layer);
 
+	/**
+	 * Controls how this quad should be rendered in item form.
+	 *
+	 * <p>If set to {@code null}, {@link ModelHelper#getSpriteInfo(TextureAtlasSprite)} will be used to retrieve
+	 * the {@linkplain RenderType item RenderType}. Set to another value to override this behavior.
+	 *
+	 * <p>The default value is {@code null}.
+	 */
```
Comment (PepperCode1) [inline fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/client/renderer/v1/mesh/MutableQuadView.java:380]: Add

```
<p>This property is respected only in item contexts. It will not have an effect in other contexts.
```

after the default value paragraph.

File: fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/client/renderer/v1/model/ModelHelper.java [hunk 4]
```diff
@@ -37,11 +45,43 @@ public final class ModelHelper {
 	/** @see #faceFromIndex(int) */
 	private static final Direction[] FACES = Arrays.copyOf(Direction.values(), 7);
 
+	private static final Map<TextureAtlasSprite, BakedQuad.SpriteInfo> SPRITE_INFOS = new ConcurrentHashMap<>();
```
Comment (PepperCode1) [inline fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/client/renderer/v1/model/ModelHelper.java]: Without weak keys or an explicit clear on resource reload, this will leak a lot of memory.

File: fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/client/renderer/v1/model/ModelHelper.java [hunk 5]
```diff
@@ -37,11 +45,43 @@ public final class ModelHelper {
...
+	 * Gets or computes a {@link BakedQuad.SpriteInfo} for a {@link TextureAtlasSprite}.
+	 *
+	 * <p>This method checks the entire sprite's {@linkplain Transparency transparency} instead of
+	 * only what a quad uses.
+	 */
+	public static BakedQuad.SpriteInfo getSpriteInfo(TextureAtlasSprite sprite) {
+		return SPRITE_INFOS.computeIfAbsent(sprite, _ -> {
+			Transparency transparency = sprite
+					.contents()
+					.computeTransparency(0.0f, 0.0f, 1.0f, 1.0f);
```
Comment (PepperCode1) [inline fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/client/renderer/v1/model/ModelHelper.java]: This should mirror vanilla; see `FaceBakery.computeMaterialTranslucency`. The cache should be removed since the result will depend on UVs as well.

File: fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/renderer/sprite/ModelManager1Mixin.java [hunk 6]
```diff
@@ -49,9 +49,9 @@ abstract class ModelManager1Mixin implements SpriteGetter {
 
 	@Override
 	public SpriteFinder spriteFinder(Identifier atlasTextureId) {
```
Comment (PepperCode1) [inline fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/renderer/sprite/ModelManager1Mixin.java]: Why was this method changed to accept IDs instead of texture locations?

File: fabric-renderer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/renderer/client/FrameBlockStateModel.java [hunk 7]
```diff
@@ -129,20 +130,25 @@ public void collectParts(RandomSource random, List<BlockModelPart> parts) {
...
-	public TextureAtlasSprite particleIcon() {
-		return frameModel.particleIcon();
+	public Material.Baked particleMaterial() {
+		return frameModel.particleMaterial();
 	}
 
 	@Override
-	public TextureAtlasSprite particleIcon(BlockAndTintGetter level, BlockPos pos, BlockState state) {
+	public boolean hasTranslucency() {
+		return false;
```
Comment (PepperCode1) [inline fabric-renderer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/renderer/client/FrameBlockStateModel.java]: Should be `return true`.

File: fabric-renderer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/renderer/client/PillarBlockStateModel.java [hunk 8]
```diff
@@ -145,13 +146,20 @@ public void resolveDependencies(Resolver resolver) {
...
+			Material.Baked[] materials = new Material.Baked[MATERIALS.size()];
+			boolean hasTranslucency = false;
+
+			for (int i = 0; i < materials.length; ++i) {
+				Material.Baked material = baker.materials()
+						.get(MATERIALS.get(i), this);
+				materials[i] = material;
+				hasTranslucency |= material.forceTranslucent() || material.sprite()
+						.contents()
+						.computeTransparency(0.0f, 0.0f, 1.0f, 1.0f)
```
Comment (PepperCode1) [inline fabric-renderer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/renderer/client/PillarBlockStateModel.java]: Seems a little questionable and there are additional decisions that need to be made with regards to `hasTranslucency` in general. Nothing to change until those desicions are made.

File: fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/mesh/EncodingFormat.java
Comment (PepperCode1) [inline fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/mesh/EncodingFormat.java]: This is not the format that is used anymore so it doesn't make sense to keep this local. It and anything that depends on it should be removed/replaced accordingly with existing constants.

File: fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/mesh/EncodingFormat.java [hunk 9]
```diff
@@ -71,7 +74,7 @@ private EncodingFormat() { }
 		VERTEX_V = VERTEX_U + 1;
 		VERTEX_LIGHTMAP = HEADER_STRIDE + 6;
 		VERTEX_NORMAL = HEADER_STRIDE + 7;
-		VERTEX_STRIDE = format.getVertexSize() / 4;
+		VERTEX_STRIDE = (format.getVertexSize() + INDIGO_VERTICES_AND_PADDING) / 4;
```
Comment (PepperCode1) [inline fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/mesh/EncodingFormat.java]: Not sure what the best way to express this is but even just hardcoding `8` makes more sense than this computation.

File: fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/ItemRenderContext.java [hunk 10]
```diff
@@ -100,20 +92,14 @@ public void renderItem(
...
 	}
 
 	private void bufferQuads(List<BakedQuad> vanillaQuads, MeshView mesh) {
 		QuadEmitter emitter = getEmitter();
 
-		final int vanillaQuadCount = vanillaQuads.size();
-
-		for (int i = 0; i < vanillaQuadCount; i++) {
-			final BakedQuad q = vanillaQuads.get(i);
+		for (final BakedQuad q : vanillaQuads) {
```
Comment (PepperCode1) [inline fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/ItemRenderContext.java]: For each loops are avoided in Indigo to avoid allocating an iterator. This should be reverted.

File: fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/SimpleBlockRenderContext.java [hunk 11]
```diff
@@ -81,12 +81,8 @@ protected void bufferQuad(MutableQuadViewImpl quad) {
 
 	private void tintQuad(MutableQuadViewImpl quad) {
 		if (quad.tintIndex() != -1) {
-			final float red = this.red;
-			final float green = this.green;
-			final float blue = this.blue;
-
 			for (int i = 0; i < 4; i++) {
-				quad.color(i, ARGB.scaleRGB(quad.color(i), red, green, blue));
+				quad.color(i, ARGB.scaleRGB(quad.color(i), this.tint));
```
Comment (PepperCode1) [inline fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/SimpleBlockRenderContext.java]: Keep the old code structure with the local. It avoids having to retrieve the field 4 times. Realistically I'm not sure it makes a difference but we shouldn't deviate from this standard without further thought.

File: fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/mixin/client/indigo/renderer/BlockRenderDispatcherMixin.java [hunk 12]
```diff
@@ -28,34 +29,67 @@
...
 	private ModelBlockRenderer modelRenderer;
 
-	@Inject(method = "renderBreakingTexture(Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/BlockAndTintGetter;Lcom/mojang/blaze3d/vertex/PoseStack;Lcom/mojang/blaze3d/vertex/VertexConsumer;)V", at = @At(value = "INVOKE_ASSIGN", target = "Lnet/minecraft/client/renderer/block/BlockModelShaper;getBlockModel(Lnet/minecraft/world/level/block/state/BlockState;)Lnet/minecraft/client/renderer/block/model/BlockStateModel;"), cancellable = true)
-	private void afterGetModel(BlockState blockState, BlockPos blockPos, BlockAndTintGetter level, PoseStack poseStack, VertexConsumer vertexConsumer, CallbackInfo ci, @Local(name = "model") BlockStateModel model) {
+	@Definition(
+			id = "getBlockModel",
+			method = "Lnet/minecraft/client/renderer/block/BlockModelShaper;getBlockModel(Lnet/minecraft/world/level/block/state/BlockState;)Lnet/minecraft/client/renderer/block/model/BlockStateModel;"
+	)
+	@Expression("? = ?.getBlockModel(?)")
+	@Inject(
```
Comment (PepperCode1) [inline fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/mixin/client/indigo/renderer/BlockRenderDispatcherMixin.java]: This is not the right way to implement this. If the method only takes a `BakedQuadOutput`, it should work with the output. To support FRAPI, add a new method to `FabricBlockRenderDispatcher` that accepts the buffer source instead, and redirects to a method in `Renderer` like other methods in FRAPI extensions interfaces.

**Review by PepperCode1 — CHANGES_REQUESTED** [review]

File: fabric-renderer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/renderer/client/PillarBlockStateModel.java (hunk 8 above)
Comment (sylv256) [reply fabric-renderer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/renderer/client/PillarBlockStateModel.java]: Okay, so no translucency on pillars then?

File: fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/renderer/sprite/ModelManager1Mixin.java (hunk 6 above)
Comment (sylv256) [reply fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/renderer/sprite/ModelManager1Mixin.java]: I don't know, it just makes more sense than directly providing the location to the PNG. There's a distinction between the two in `QuadAtlas` now as locations used to be confused with the actual IDs, and they can be useful sometimes.

File: fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/client/renderer/v1/model/ModelHelper.java (hunk 5 above)
Comment (sylv256) [reply fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/client/renderer/v1/model/ModelHelper.java]: If we store it in the quads, then it should be fine as long as it's never called too much outside of baking or initial construction. We can put a notice about that on this method and on the `getOrResolve` methods on `QuadView`.

File: fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/renderer/sprite/ModelManager1Mixin.java (hunk 6 above)
Comment (sylv256) [reply fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/renderer/sprite/ModelManager1Mixin.java]: I think it makes more sense to use the actual ID when _finding_ (& identifying) the `SpriteFinder`.

File: fabric-renderer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/renderer/client/OctagonalColumnGeometry.java [hunk 13]
```diff
@@ -70,6 +73,7 @@ public QuadCollection bake(TextureSlots textures, ModelBaker baker, ModelState s
 		emitter.cullFace(Direction.UP);
 		emitter.spriteBake(sprite, MutableQuadView.BAKE_LOCK_UV);
 		emitter.shadeMode(shadeMode);
+		ModelHelper.setSpriteInfo(emitter, material);
```
Comment (sylv256) [inline fabric-renderer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/renderer/client/OctagonalColumnGeometry.java]: Can these be inlined into `QuadEmitter` or MQV? This is kind of verbose for something that will be used quite a lot.

File: fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/renderer/sprite/ModelManager1Mixin.java (hunk 6 above)
Comment (PepperCode1) [reply fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/renderer/sprite/ModelManager1Mixin.java]: I agree after seeing more of the vanilla code.

File: fabric-renderer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/renderer/client/OctagonalColumnGeometry.java (hunk 13 above)
Comment (PepperCode1) [reply fabric-renderer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/renderer/client/OctagonalColumnGeometry.java]: Fixed by turning `spriteBake` into `materialBake` that accepts a `Material.Baked` instead of a `TextureAtlasSprite`.

**Review by modmuss50 — APPROVED** [review]
Looks great to my untrained eye. Many thanks for this I will look at releasing this as a beta first to allow time for other mods to update to support it.

**Comment by Snownee** [comment]
Adding extra models using the new model loading api does not seem to work properly, as the event dispatcher is always null.

image

**Comment by MrCrayfish** [comment]
`hookModelCollect` in `ModelManagerMixin` I believe is targeting the wrong `thenApplyAsync`. I believe it should be an ordinal of `0` to correctly provide `ModelLoadingEventDispatcher` context when `discoverModelDependencies` is invoked.

Unless `ModelManager#buildModelGroups` was intentionally targeted, simply adding another `ModifyArg` to wrap the `thenApplyAsync` that calls `discoverModelDependencies` should resolve the issue.

**Comment by modmuss50** [comment]
Thanks @Snownee and @MrCrayfish for finding this and providing the fix, I have gone ahead and commited the fix for the next release: https://github.com/FabricMC/fabric-api/commit/e037b8e3e86698205c438190b7cb78a683af82bb This will be out in the next 26.1.1 beta that will also be marked as compatible with 26.1(.0).

Please dont hesitate to create issues, it was only by chance that I saw these comments.
