### PR TITLE
Fix FabricBlockLootTableProvider breaking depending on the mapping set

### LINKED ISSUE #3069: FabricBlockLootTableProvider breaks depending on the mapping set
This affects all Fabric APIs from Minecraft 1.19.3 onwards.

## A Brief Background

`FabricBlockLootTableProvider` implements `FabricLootTableProvider`. `FabricLootTableProvider` extends a `Consumer` which is used to register the loot table entries to be written to the disk. The consumer itself is implemented within `FabricBlockLootTableProvider#accept` which implements the registration method.

https://github.com/FabricMC/fabric/blob/926dc7fcc3b8096d7c395ee351d23fbe6193839c/fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricBlockLootTableProvider.java#L79-L114

## What is `#accept`?

It would be fine if `#accept` was just the name of the method passed into the `Consumer`. However, it is also the yarn mapping name for `BlockLootTableGenerator#accept`. In Yarn mappings, this is fine as `#accept` would then override `Consumer#accept` and implement perfectly. However, in other mapping sets, such as Mojmaps, the name is `BlockLootSubProvider#generate`. This requires a modder using Mojmaps to implement the `#accept` method from the Consumer and delegate to `BlockLootSubProvider#generate`.

This is an issue since it means that the code is reliant upon the mapping set. You need to add the method in non-Yarn mappings sets and remove the method in Yarn mapping sets, otherwise the call would infinitely recurse.

## Possible Solution

Because of how Fabric implements loot table providers, the main solution would be to change `FabricLootTableProvider` to extend `LootTableGenerator` and call the associated method. This would prevent any disambiguation between mapping sets as the method's name would then change according to which mapping set it was apart of, rather than be static from the `Consumer`.

### PR DESCRIPTION
**Pull request by Technici4n**
Fixes #3069.

Also removes unnecessary internal methods from `FabricLootTableProvider` by moving the `run` logic to an impl method.

This is not a breaking change assuming modders used the API as intended.

### CODE REVIEW

**Comment by ChampionAsh5357** [comment]
So, I don't understand how this fixes the issue, since it still persists. You still need to implement `#accept` to delegate to `#generate` in Mojang's mapping set. Once again, I will suggest just simply changing the `Consumer` to `LootTableGenerator` so that the generator is not dependent on the mapping set to determine whether the method is implemented or not.

**Review by modmuss50 — CHANGES_REQUESTED** [review]
~~Yes, I fail to see how this resolves the issue.~~

**Comment by Technici4n** [comment]
It should fix the issue by removing the requirement for an implementation of `Consumer<BiConsumer<...>>`. So `SimpleFabricLootTableProvider#accept` will remain `#accept` when mapped to intermediary as it does not override a Minecraft method, whereas `FabricBlockLootTableProvider#accept` will correctly get remapped to `method_<...>` then back to `generate` in mojmap environments. Since the `Consumer` superinterface is gone, there will not be a compile error.

I will investigate the alternative approach, however I should say that removing `getLootContextType`, `getFabricDataOutput`, and `run` from `FabricLootTableProvider` makes the code flow much easier to understand IMO, and should be done either way.

**Comment by modmuss50** [comment]
Maybe im wrong, I did only have a quick look at it. I will need to get setup to actually test this.

**Comment by ChampionAsh5357** [comment]
> It should fix the issue by removing the requirement for an implementation of Consumer<BiConsumer<...>>. So SimpleFabricLootTableProvider#accept will remain #accept when mapped to intermediary as it does not override a Minecraft method, whereas FabricBlockLootTableProvider#accept will correctly get remapped to method_<...> then back to generate in mojmap environments. Since the Consumer superinterface is gone, there will not be a compile error.

I think this is my bad as well. I set up Fabric for the first time on my machine to test it, and it seems I forgot to switch to the PR branch. Apologies, I believe the solution should work fine.

**Comment by Technici4n** [comment]
I confirmed that this works by cherry-picking to 1.19.4, publishing to maven local via `gradlew clean build publishToMavenLocal` and then depending on it in AE2 (needed a 1.19.4 mojmap project). If you want to do that too, make sure to uncomment `repositories.mavenLocal()` in the Fabric API `build.gradle` and add maven local to your project's repositories. If you want to test in 1.19.4 you can use that branch: https://github.com/Technici4n/fabric/tree/fix-3069.

Could probably use extra testing by someone else, but now I'm fully certain that this fix works. Whether it should be backported to 1.19.4 is up for debate... :smile:

**Comment by Technici4n** [comment]
Using `LootTableGenerator` would also work, indeed. It only has a single `accept` method.

Is it useful to have an `accept(BiConsumer<Identifier, LootTable.Builder> exporter)` method in `FabricLootTableProvider`, or not? I don't think one would ever use it. If not we can keep the current PR, if yes I will add it back.

For 1.19.4 I think replacing the `Consumer` superinterface by a `LootTableGenerator` is a good fix, however I'd like to clean up the code for 1.20.

EDIT: opened 1.19.4 version: #3071.

**Comment by ChampionAsh5357** [comment]
> Is it useful to have an accept(BiConsumer<Identifier, LootTable.Builder> exporter) method in FabricLootTableProvider, or not? I don't think one would ever use it. If not we can keep the current PR, if yes I will add it back.

Since Fabric doesn't use Mojang's method of generator entries in a single loot table provider, I would say it really just depends on how much logic you want to delegate to the already existing implementations. The Fabric implementation only provides separation of loot table providers, so it's just purely a matter of compatibility if somebody wanted to use Mojang's method of registering a loot table provider instead.

File: fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/impl/datagen/loot/LootTableProviderImpl.java [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+import net.minecraft.loot.context.LootContextType;
+import net.minecraft.util.Identifier;
+
+import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
+import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider;
+import net.fabricmc.fabric.api.datagen.v1.provider.SimpleFabricLootTableProvider;
+import net.fabricmc.fabric.api.resource.conditions.v1.ConditionJsonProvider;
+import net.fabricmc.fabric.impl.datagen.FabricDataGenHelper;
+
+public class LootTableProviderImpl {
```
Comment (modmuss50) [inline fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/impl/datagen/loot/LootTableProviderImpl.java]: Nit: final + private constructor

**Comment by Technici4n** [comment]
> > Is it useful to have an accept(BiConsumer<Identifier, LootTable.Builder> exporter) method in FabricLootTableProvider, or not? I don't think one would ever use it. If not we can keep the current PR, if yes I will add it back.
> 
> Since Fabric doesn't use Mojang's method of generator entries in a single loot table provider, I would say it really just depends on how much logic you want to delegate to the already existing implementations. The Fabric implementation only provides separation of loot table providers, so it's just purely a matter of compatibility if somebody wanted to use Mojang's method of registering a loot table provider instead.

Then I will add `LootTableGenerator` too, it doesn't hurt.

File: fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/impl/datagen/loot/LootTableProviderImpl.java (hunk 1 above)
Comment (Technici4n) [reply fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/impl/datagen/loot/LootTableProviderImpl.java]: It's an impl class so I didn't bother, why not though.

Comment (modmuss50) [reply fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/impl/datagen/loot/LootTableProviderImpl.java]: I guess, I think generally we try to, but its not a problem if its forgotten.
