### PR TITLE
Handle null being passed as the datafix type to PersistentState.Type

### LINKED ISSUE #3327: Persistent state types should support null data fixer types
As of Minecraft 1.20.2, persistent state types must be constructed with a data fixer type. If the data fixer type is `null`, then the following exception will be logged when loading the persistent state:

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.datafixer.DataFixTypes.update(com.mojang.datafixers.DataFixer, net.minecraft.nbt.NbtCompound, int, int)" because "dataFixTypes" is null
```

### PR DESCRIPTION
**Pull request by modmuss50**
Closes #3327

The discoverbility is low, however I think most people will first try null and then realise it crashes. At the moment this is by far the easyist fix.

### CODE REVIEW

File: fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/mixin/object/builder/PersistentStateManagerMixin.java [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+import org.spongepowered.asm.mixin.injection.Inject;
+import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;
+import org.spongepowered.asm.mixin.injection.callback.LocalCapture;
+
+import net.minecraft.datafixer.DataFixTypes;
+import net.minecraft.nbt.NbtCompound;
+import net.minecraft.world.PersistentStateManager;
+
+@Mixin(PersistentStateManager.class)
+public class PersistentStateManagerMixin {
```
Comment (Juuxel) [inline fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/mixin/object/builder/PersistentStateManagerMixin.java]:
```suggestion
class PersistentStateManagerMixin {
```
(see conventions)

**Review by Juuxel — APPROVED** [review]

File: fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/mixin/object/builder/PersistentStateManagerMixin.java (hunk 1 above)
Comment (modmuss50) [reply fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/mixin/object/builder/PersistentStateManagerMixin.java]: Probably another thing we should validate 👍

**Review by haykam821 — APPROVED** [review]
