### PR TITLE
Fix default fluid names for non-placeable fluids, clarify Storage iterator lifecycle with modification

### LINKED ISSUE #3114: Injected getFluidName method for fluids
Currently, if you only want to provide a name for a fluid that has no block, it's pretty cumbersome and needs you register an additional object like this:

```java
FluidVariantAttributes.register(MY_FLUID, new FluidVariantAttributeHandler() {
    @Override
    public Text getName(FluidVariant variant) {
        return Text.translatable("fluid.my_mod.my_fluid");
    }
});
```
I'm proposing a `FabricFluid` injected interface with these methods:
```java
public interface FabricFluid {
    default Text getFluidName() {
        // the current default in FluidVariantAttributeHandler
        return ((Fluid) this).getDefaultState().getBlockState().getBlock().getName();
    }

    // If this interface is part of the transfer API:
    default Text getFluidName(FluidVariant variant) {
        return getFluidName();
    }
}
```

The default fluid variant attribute handler would then delegate to these methods.

(`getFluidName` so that a fluid class doesn't end up inheriting both this unobfuscated method and `method_5477` - present in many classes such as [`Nameable`](https://github.com/FabricMC/yarn/blob/de6b90b586e5fe8cb814a134cb3bb9a307acd8a6/mappings/net/minecraft/util/Nameable.mapping#L10) - which would cause a remapping conflict)

### LINKED ISSUE #3123: Define that `Storage#iterator` must be inside of a transaction if modification is expected.
See discussion at https://discord.com/channels/507304429255393322/566417932503089232/1118520686625968209.

### PR DESCRIPTION
**Pull request by Technici4n**
Fixes #3114. Fixes #3123.

### CODE REVIEW

**Review by modmuss50 — APPROVED** [review]

File: fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/fluid/FluidVariantAttributeHandler.java [hunk 1]
```diff
@@ -41,7 +45,14 @@ public interface FluidVariantAttributeHandler {
 	 * Return the name that should be used for the passed fluid variant.
 	 */
 	default Text getName(FluidVariant fluidVariant) {
-		return fluidVariant.getFluid().getDefaultState().getBlockState().getBlock().getName();
+		Block fluidBlock = fluidVariant.getFluid().getDefaultState().getBlockState().getBlock();
+
+		if (fluidBlock == Blocks.AIR) {
```
Comment (Juuxel) [inline fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/fluid/FluidVariantAttributeHandler.java]: This check for `fluidVariant.getFluid() != Fluids.EMPTY` as the translation key would be different from the current one and would have no translation.

**Review by Juuxel — CHANGES_REQUESTED** [review]

File: fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/fluid/FluidVariantAttributeHandler.java (hunk 1 above)
Comment (Technici4n) [reply fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/fluid/FluidVariantAttributeHandler.java]: Whoops thank you so much, this is embarrassing. 😄

**Review by Juuxel — APPROVED** [review]
