### PR TITLE
Configuration networking fixes

### LINKED ISSUE #3821: Assertion error when re-entering configuration.
Crashes when Fabric 1.20.6 (latest) is opened in idea and bungeecord world travel is performed
(For example: cubecraft)

### LINKED ISSUE #3830: Custom Payload cannot be sent in ClientConfigurationConnectionEvents.INIT
# Description
ClientConfigurationConnectionEvents.DISCONNECT and READY are both telling me not to send any packets. However, I also cannot send packet in the INIT event because when then INIT event fired, the connections are still in LOGIN state.

I tried to investigate fabric api's code, the INIT events are all fired after the packet listener constructors are called, however, the new packet listener constructor called does not mean the connection moved into a new state, see code before.

Since INIT might mean constructor, I don't know if this is a bug. if not, then we have no events to send packets in configuration phase.
# Environment
fabric api: 0.99.5+1.21
mc: 1.21 pre3
# Reason
```java
// net.minecraft.client.network.ClientLoginNetworkHandler
    public void onSuccess(LoginSuccessS2CPacket packet) {
        this.switchTo(ClientLoginNetworkHandler.State.JOINING);
        GameProfile gameProfile = packet.profile();
        this.connection.transitionInbound(ConfigurationStates.S2C, new ClientConfigurationNetworkHandler(this.client, this.connection, new ClientConnectionState(gameProfile, this.client.getTelemetryManager().createWorldSession(this.newWorld, this.worldLoadTime, this.minigameName),  newClientDynamicRegistryType.createCombinedDynamicRegistries().getCombinedRegistryManager(), FeatureFlags.DEFAULT_ENABLED_FEATURES, (String)null, this.serverInfo, this.parentScreen, this.serverCookies, (ChatHud.ChatState)null, packet.strictErrorHandling(), Map.of(), ServerLinks.EMPTY)));
        // ClientConfigurationConnectionEvents.INIT fired at the new ClientConfigurationNetworkHandler statement above
        this.connection.send(EnterConfigurationC2SPacket.INSTANCE);
        this.connection.transitionOutbound(ConfigurationStates.C2S);
        this.connection.send(new CustomPayloadC2SPacket(new BrandCustomPayload(ClientBrandRetriever.getClientModName())));
        this.connection.send(new ClientOptionsC2SPacket(this.client.options.getSyncedOptions()));
        // should inject here, after the client and server entered configuration phase
    }
```

### PR DESCRIPTION
**Pull request by modmuss50**
- Deprecate `ClientConfigurationConnectionEvents.READY` as it was incorrectly named, replaced with `COMPLETE`
- Add `ClientConfigurationConnectionEvents.START`, this is fired when the server is ready to recieve configuration packets. During login and reconfigure
- Remove incorrect assertion causing a crash when reconfiguring.

This should be backported to 1.20.6

Closes #3830
Closes #3821

### CODE REVIEW

**Comment by zly2006** [comment]
Please refer to https://github.com/FabricMC/fabric/pull/3831/commits/ae314ad27769325468c4cccbcfa47f905c56eac8 , we have to wait for initial acceptable channels from server, so `ClientConfigurationNetworking.canSend` could work.

File: fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientConfigurationNetworkAddon.java [hunk 1]
```diff
@@ -53,6 +53,11 @@ protected void invokeInitEvent() {
 		ClientConfigurationConnectionEvents.INIT.invoker().onConfigurationInit(this.handler, this.client);
 	}
 
+	@Override
+	public void onServerReady() {
+		ClientConfigurationConnectionEvents.START.invoker().onConfigurationStart(this.handler, this.client);
```
Comment (zly2006) [inline fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientConfigurationNetworkAddon.java:58]: and you forgot to call super

File: fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientConfigurationNetworkAddon.java [hunk 2]
```diff
@@ -53,6 +53,11 @@ protected void invokeInitEvent() {
...
+	}
```
Comment (zly2006) [inline fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientConfigurationNetworkAddon.java:62]:
```suggestion
        super. onServerReady();
	}
```

File: fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/mixin/networking/client/ClientPlayNetworkHandlerMixin.java [hunk 3]
```diff
@@ -56,6 +58,12 @@ private void handleServerPlayReady(GameJoinS2CPacket packet, CallbackInfo ci) {
 		this.addon.onServerReady();
 	}
 
+	@Inject(method = "onEnterReconfiguration", at = @At("RETURN"))
```
Comment (zly2006) [inline fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/mixin/networking/client/ClientPlayNetworkHandlerMixin.java]: please remove this call, onServerReady should be invoked when initial channels are received.

Comment (zly2006) [reply fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/mixin/networking/client/ClientPlayNetworkHandlerMixin.java]: `net.fabricmc.fabric.mixin.networking.client.ClientLoginNetworkHandlerMixin#handleConfigurationReady` should also be removed

File: fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientConfigurationNetworkAddon.java [hunk 4]
```diff
@@ -53,6 +53,11 @@ protected void invokeInitEvent() {
...
+
 	@Override
 	protected void receiveRegistration(boolean register, RegistrationPayload payload) {
 		super.receiveRegistration(register, payload);
```
Comment (zly2006) [inline fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientConfigurationNetworkAddon.java:66]: The configuration negotiation flow should be like this, imo:
S2C: LoginSuccessS2CPacket
C2S: EnterConfigurationC2SPacket
S2C: sendInitialChannelRegistrationPacket
S2C: Ping
S: fire ServerConfigurationConnectionEvents.BEFORE_CONFIGURE
C2S: receive initial channels, send back client side channels, **fire START event here because we must wait for server initial channels**
C2S: Pong
S: receive initial channels, fire ServerConfigurationConnectionEvents.CONFIGURE

so onServerReady() should be called here (in the if block) as we received the initial channels.

File: fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientConfigurationNetworkAddon.java (hunk 2 above)
Comment (zly2006) [reply fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientConfigurationNetworkAddon.java:62]: call super to set isServerReady = true

File: fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientConfigurationNetworkAddon.java (hunk 4 above)
Comment (modmuss50) [reply fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientConfigurationNetworkAddon.java:66]: Yes, I agree ill make these changes. It should also be fired even when connecting to a vanilla server (thus when no channels are recieved)

Comment (modmuss50) [reply fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientConfigurationNetworkAddon.java:66]: I have updated this to now also trigger the event it if the brand packet is recieved.

**Review by zly2006 — APPROVED** [review]

File: fabric-networking-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/networking/client/configuration/NetworkingConfigurationClientTest.java [hunk 5]
```diff
@@ -29,5 +35,16 @@ public void onInitializeClient() {
 			// Respond back to the server that the task is complete
 			context.responseSender().sendPacket(NetworkingConfigurationTest.ConfigurationCompletePacket.INSTANCE);
 		});
+
+		ClientConfigurationConnectionEvents.START.register((handler, client) -> {
+			if (!ClientConfigurationNetworking.canSend(NetworkingConfigurationTest.ConfigurationStartPacket.ID)) {
+				// This isn't fatal as it will happen when connecting to a vanilla server.
+				LOGGER.warn("Can send failed in configuration networking events");
```
Comment (Octol1ttle) [inline fabric-networking-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/networking/client/configuration/NetworkingConfigurationClientTest.java]:
```suggestion
				LOGGER.warn("Not sending configuration start packet; is this a vanilla server?");
```
