### PR TITLE
Fix AFTER_SETUP event not being able to render

### LINKED ISSUE #4195: WorldRenderEvents.AFTER_SETUP fires immediately before a glClear() preventing rendering in MC 1.21.3
Minecraft added a `glClear` call right after the `WorldRenderEvents.AFTER_SETUP` call is fired, preventing any rendering from happening during that event.

This is a blocking issue for Distant Horizons since the next event in the stack `BEFORE_ENTITIES` is fired too late in Minecraft's rendering pipeline (I need to draw into the skybox).
If this is expected behavior moving forward please let me know so I can look into other solutions, thanks!

### Previous behavior: MC 1.21.1 
Fabric API `0.107.0+1.21.1`

**Final Frame:**
image

**Render Doc OpenGL event list:**
image

------

### New behavior: MC 1.21.3
Fabric API `0.107.0+1.21.3`

**Final Frame:**
image

**Render Doc OpenGL event list:**
image

-----

Here are render doc snapshots of both Minecraft versions in case you want to look closer:
[render dock snapshots.zip](https://github.com/user-attachments/files/17564672/render.dock.snapshots.zip)

### PR DESCRIPTION
**Pull request by JustRed23**
Due to 1.21.2 changing the way how level rendering works, adding a `RenderSystem.clear` after the `AFTER_SETUP` event, rendering is not possible with this event, so I moved the event to a later point after the clear call but before the terrain rendering

### CODE REVIEW

File: fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/WorldRendererMixin.java [hunk 1]
```diff
@@ -83,6 +83,19 @@ private void afterTerrainSetup(Camera camera, Frustum frustum, boolean hasForced
...
 
+	@Inject(
+			method = "method_62214",
+			at = @At(
+				value = "INVOKE",
+				target = "Lnet/minecraft/util/profiler/Profiler;push(Ljava/lang/String;)V",
+				ordinal = 0,
+				shift = Shift.AFTER
+			)
+	)
```
Comment (Alexander01998) [inline fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/WorldRendererMixin.java]: This points to `profiler.push("terrain");` if I'm not mistaken? Might be a good idea to note that with a comment since it's not obvious from the code.

Comment (JustRed23) [reply fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/WorldRendererMixin.java]: It does, I'll add a comment

File: fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/WorldRenderEvents.java [hunk 2]
```diff
@@ -68,13 +69,26 @@ private WorldRenderEvents() { }
 	 * identified and rebuilt but before chunks are uploaded to GPU.
 	 *
 	 * <p>Use for setup of state that depends on view frustum.
+	 *
+	 * <b>Can NOT be used to render anything after MC 1.21.2 due to a glClear call, use {@link WorldRenderEvents#BEFORE_TERRAIN} instead.
```
Comment (watertrainer) [inline fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/WorldRenderEvents.java]: building fails for me because of a missing closing tag for the bold text here, works after adding it

Comment (JustRed23) [reply fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/WorldRenderEvents.java]: Weird.. the rest of the docs also don't use closing tags

Comment (Juuxel) [reply fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/WorldRenderEvents.java]: The docs don't use closing tags for `<p>`. That format is pretty conventional for javadocs, and I think it's a special case in the Checkstyle rules. (In valid HTML, the end tag `</b>` can't be omitted but `</p>` can in this case.)

Comment (AsynchronousAI) [reply fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/WorldRenderEvents.java]: I got this issue also, adding `</b>` fixed this.

**Comment by AsynchronousAI** [comment]
LGTM!

**Review by Alexander01998 — APPROVED** [review]

**Review by modmuss50 — CHANGES_REQUESTED** [review]
It was pointed out to me on discord that the old API is broken, this should be fixed to work as it did it before (or as close to it). There is no point adding a new api and leaving a broken API in its place.

**Comment by JustRed23** [comment]
> It was pointed out to me on discord that the old API is broken, this should be fixed to work as it did it before (or as close to it). There is no point adding a new api and leaving a broken API in its place.

Removed new event, fixed existing event

**Review by modmuss50 — APPROVED** [review]

File: fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/WorldRendererMixin.java [hunk 3]
```diff
@@ -80,6 +80,18 @@ private void beforeRender(ObjectAllocator objectAllocator, RenderTickCounter tic
 	@Inject(method = "setupTerrain", at = @At("RETURN"))
 	private void afterTerrainSetup(Camera camera, Frustum frustum, boolean hasForcedFrustum, boolean spectator, CallbackInfo ci) {
 		context.setFrustum(frustum);
+	}
+
+	@Inject(
+			method = "method_62214",
+			at = @At(
+				value = "INVOKE",
```
Comment (Chocohead) [inline fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/WorldRendererMixin.java]: Would this not be a good place to use `INVOKE_STRING`? That way this can specifically target the `terrain` profiler push call, even if it gets moved around

**Review by Verteiron — APPROVED** [review]
